# Generated by Django 4.0.6 on 2022-07-14 13:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('foundation_year', models.PositiveIntegerField(blank=True, default=2022, help_text='<b>Year of foundation</b>', null=True)),
                ('bio', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'showroom',
            },
        ),
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 7, 14, 13, 28, 48, 783499))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 8, 13, 13, 28, 48, 783517))),
                ('discount_amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_discount', to='showroom.showroom', verbose_name='showroom')),
            ],
            options={
                'db_table': 'showroom_discount',
            },
        ),
    ]
