# Generated by Django 4.0.6 on 2022-07-14 13:39

import abstract.models
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountshowroom',
            name='end_date',
            field=models.DateTimeField(default=abstract.models.thirty_day_hence),
        ),
        migrations.AlterField(
            model_name='discountshowroom',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
