# Generated by Django 4.0.6 on 2022-07-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
        ('provider', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromProviderToShowroomDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.car')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.provider')),
                ('providers_discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.discountprovider')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showroom.showroom')),
            ],
            options={
                'db_table': 'sales_provider_to_showroom',
            },
        ),
        migrations.CreateModel(
            name='FormShowroomToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showroom.showroom')),
                ('showroom_discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showroom.discountshowroom')),
            ],
            options={
                'db_table': 'sales_showroom_to_customer',
            },
        ),
    ]
