# Generated by Django 4.0.6 on 2022-07-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
        ('customer', '0001_initial'),
        ('provider', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormShowroomToCustomer',
            new_name='FormShowroomToCustomerDeal',
        ),
        migrations.RenameModel(
            old_name='FromProviderToShowroomDeals',
            new_name='FromProviderToShowroomDeal',
        ),
    ]
